default: &default
 adapter: postgresql
 database: loveschmove
 # username: pguser
 # password: password
 encoding: unicode
 pool: 5
 timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
